name: Report Progress to Roadmap

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # Run daily at 12:00 UTC to ensure regular updates
    - cron: '0 12 * * *'

jobs:
  report-progress:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Analyze app progress (ENHANCED)
      id: analyze
      run: |
        # Determine app name from repository
        REPO_NAME="${GITHUB_REPOSITORY##*/}"
        APP_KEY="journal-summarizer"  # Fixed mapping
        
        echo "app_key=$APP_KEY" >> $GITHUB_OUTPUT
        echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
        
        # Enhanced progress analysis based on breakthrough achievements
        progress=0
        status="created"
        features=()
        
        # Check breakthrough deployment achievements
        if [[ -f "web/index.html" ]]; then
          progress=$((progress + 15))
          features+=("Direct HTML Deployment")
        fi
        
        if [[ -f "package.json" && -f "vercel.json" ]]; then
          progress=$((progress + 15))
          features+=("Vercel Integration")
        fi
        
        # Check backend achievements  
        if [[ -d "backend" && -f "backend/main.py" ]]; then
          progress=$((progress + 20))
          features+=("Railway Backend API")
        fi
        
        # Check AI service integration
        if [[ -f "backend/app/services/ai_service.py" || -f "backend/app/services/ai_service_enhanced.py" ]]; then
          progress=$((progress + 20))
          features+=("AI Integration (Groq)")
        fi
        
        # Check documentation (major achievement)
        if [[ -f "DEPLOYMENT_BREAKTHROUGH.md" ]]; then
          progress=$((progress + 10))
          features+=("Comprehensive Documentation")
        fi
        
        # Check deployment configuration
        if [[ -f "docker-compose.yml" && -f ".github/workflows/report-progress.yml" ]]; then
          progress=$((progress + 10))
          features+=("CI/CD Pipeline")
        fi
        
        # Enhanced status determination based on our breakthrough
        if [[ $progress -ge 70 ]]; then
          status="beta"  # Production deployment working, needs features
        elif [[ $progress -ge 50 ]]; then
          status="alpha" # Major systems working
        elif [[ $progress -ge 30 ]]; then
          status="development" # Active development
        elif [[ $progress -ge 10 ]]; then
          status="started" # Project initiated
        fi
        
        echo "progress=$progress" >> $GITHUB_OUTPUT
        echo "status=$status" >> $GITHUB_OUTPUT
        echo "features=${features[*]}" >> $GITHUB_OUTPUT
        
        # Count files and commits
        file_count=$(find . -name "*.js" -o -name "*.html" -o -name "*.py" -o -name "*.json" -o -name "*.md" | grep -v node_modules | wc -l)
        commit_count=$(git rev-list --count HEAD)
        
        echo "file_count=$file_count" >> $GITHUB_OUTPUT
        echo "commits=$commit_count" >> $GITHUB_OUTPUT
        
        # Add breakthrough-specific metadata
        echo "breakthrough=Direct HTML deployment solving React Native Web issues" >> $GITHUB_OUTPUT
        echo "cost_achievement=\$0.00 monthly deployment cost" >> $GITHUB_OUTPUT
    
    - name: Send progress to roadmap repository
      if: github.ref == 'refs/heads/main'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const appKey = '${{ steps.analyze.outputs.app_key }}';
          const repoName = '${{ steps.analyze.outputs.repo_name }}';
          const progress = '${{ steps.analyze.outputs.progress }}';
          const status = '${{ steps.analyze.outputs.status }}';
          const features = '${{ steps.analyze.outputs.features }}';
          const fileCount = '${{ steps.analyze.outputs.file_count }}';
          const commits = '${{ steps.analyze.outputs.commits }}';
          
          // Trigger progress sync in roadmap repository
          try {
            await github.rest.repos.createDispatchEvent({
              owner: 'PCSchmidt',
              repo: 'roadmap-for-building-generative-ai-apps',
              event_type: 'app-progress-update',
              client_payload: {
                app_name: repoName,
                app_key: appKey,
                progress: parseInt(progress),
                status: status,
                features: features.split(' '),
                file_count: parseInt(fileCount),
                commits: parseInt(commits),
                timestamp: new Date().toISOString(),
                triggered_by: context.sha
              }
            });
            
            console.log(`✅ Progress reported to roadmap repository`);
            console.log(`App: ${repoName}`);
            console.log(`Progress: ${progress}%`);
            console.log(`Status: ${status}`);
            
          } catch (error) {
            console.error('Failed to report progress:', error);
            // Don't fail the workflow if reporting fails
          }
    
    - name: Create progress summary
      run: |
        cat << EOF > progress-summary.md
        # 📊 Development Progress Report
        
        **Repository:** ${{ steps.analyze.outputs.repo_name }}
        **Progress:** ${{ steps.analyze.outputs.progress }}%
        **Status:** ${{ steps.analyze.outputs.status }}
        **Features:** ${{ steps.analyze.outputs.features }}
        **Files:** ${{ steps.analyze.outputs.file_count }}
        **Commits:** ${{ steps.analyze.outputs.commits }}
        **Last Updated:** $(date)
        
        ## Next Steps
        
        Based on current progress, consider:
        
        - [ ] Add more screen components if progress < 25%
        - [ ] Implement backend API if progress < 40%
        - [ ] Add AI integration if progress < 60%
        - [ ] Add comprehensive testing if progress < 70%
        - [ ] Prepare for deployment if progress < 90%
        
        ## Development Tips
        
        - Focus on core functionality first
        - Test on mobile devices early and often
        - Document your AI integration approach
        - Create demo videos for your portfolio
        
        EOF
        
        echo "Progress summary created:"
        cat progress-summary.md
    
    - name: Upload progress summary
      uses: actions/upload-artifact@v4
      with:
        name: progress-summary
        path: progress-summary.md
        retention-days: 30
